version: '3.8'  

services:  
  mysql:  
    image: mysql:latest  
    container_name: mysql_service  
    environment:  
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: transactions_db  
      MYSQL_USER: myuser  
      MYSQL_PASSWORD: mypassword  
    ports:  
      - "3306:3306"  
    volumes:  
      - mysql_data:/var/lib/mysql  
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro  

volumes:  
  mysql_data:  